name: Fintech API CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  compose-test:
    name: Build and Test Docker Compose Stack
    runs-on: Ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker Versions
        run: |
          docker --version
          docker compose version
      
      - name: Create environment file
        run: |
          cp .env.example .env

      - name: Build Docker Compose Services
        run: |
          docker compose -f docker/docker-compose.yml build

      - name: Start Docker Compose Stack
        run: |
          docker compose -f docker/docker-compose.yml up -d

      - name: Show running containers
        run: |
          docker compose -f docker/docker-compose.yml ps

      - name: Wait for API
        run: |
          echo "Waiting for API..."

          for i in {1..30}; do
            if curl -fsS http://localhost:8000/health; then
              echo "API is healthy!"
              exit 0
            fi

            echo "API not ready yet.."
            sleep 2
          done

          echo "API failed to become healthy"
          docker compose -f docker/docker-compose.yml ps
          docker compose -f docker/docker-compose.yml logs
          exit 1

      - name: Test API health endpoint
        run: |
          curl --fail http://localhost:8000/health

      - name: Run application tests
        run: |
          docker compose -f docker/docker-compose.yml exec -T api pytest -v

      - name: Show logs on failure
        if: failure()
        run: |
          docker compose -f docker/docker-compose.yml ps
          docker compose -f docker/docker-compose.yml logs

      - name: Stop Docker Compose Stack
        if: always()
        run: |
          docker compose -f docker/docker-compose.yml down -v
          